name: Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy na VPS
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Copy files via SSH
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          source: "."
          target: ${{ secrets.PROJECT_PATH }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASS }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.PROJECT_PATH }}
            git fetch origin main
            git reset --hard origin/main
            git clean -fxd -e .env
            cp .env .env.production
            /home/nginx/.local/share/pnpm/pnpm install 
            /home/nginx/.local/share/pnpm/pnpm build
            sudo /usr/bin/systemctl restart packetads.service
            